// pub const TokenType = enum {
//     ILLEGAL,
//     EOF,

//     // Identifiers + literals,
//     IDENT,
//     INT,
//     TRUE,
//     FALSE,

//     // Operators,
//     ASSIGN,
//     PLUS,
//     MINUS,
//     BANG,
//     ASTERISK,
//     SLASH,
//     LT,
//     GT,
//     EQ,
//     NOT_EQ,
//     AND,
//     OR,
//     GTE,
//     LTE,
//     BITWISE_AND,
//     BITWISE_OR,

//     // Delimiters,
//     COMMA,
//     SEMICOLON,
//     LPAREN,
//     RPAREN,
//     LBRACE,
//     RBRACE,

//     // Keywords,
//     FUNCTION,
//     LET,
//     IF,
//     ELSE,
//     RETURN,
// };

pub const Token = union(enum) {
    ILLEGAL: []const u8,
    EOF: void,

    // Identifiers + literals,
    IDENT: []const u8,
    INT: []const u8,
    TRUE: void,
    FALSE: void,

    // Operators,
    ASSIGN: void,
    PLUS: void,
    MINUS: void,
    BANG: void,
    ASTERISK: void,

    SLASH: void,
    LT: void,
    GT: void,

    EQ: void,
    NOT_EQ: void,
    AND: void,
    OR: void,
    GTE: void,
    LTE: void,
    BITWISE_AND: void,
    BITWISE_OR: void,

    // Delimiters,
    COMMA: void,
    SEMICOLON: void,
    LPAREN: void,
    RPAREN: void,
    LBRACE: void,
    RBRACE: void,

    // Keywords,
    FUNCTION: void,
    LET: void,
    IF: void,
    ELSE: void,
    RETURN: void,
};
